글쓰기 페이지 유아이 마감
GRAM-DSM/Color_iOS pull request #5
Opened 2021-10-19 13:25 UTC by jangseoyoung

![IMG_226F838239ED-1](https://user-images.githubusercontent.com/67036711/137919207-67d6f463-c750-47ba-841c-dc84da5b1a49.jpeg)

2021-10-19 13:45 UTC, MoonJisu requested changes
그래모할때 보다 성장한게 보이는 것 같아요:)

중복되는 리뷰는 하지 않았습니다. 리뷰를 보고 동일한 내용의 코드들을 전부 고쳐주세요!
이미 알고있는 내용일 경우 코멘트 대신 이모지를 남긴 후 수정하지 않아도 좋습니다👍

2021-10-19 13:45 UTC, MoonJisu commented on Color/Color/VC/WritingPageViewController.swift
> +    @IBAction private func redButton(_ sender: UIButton) {
Rx를 이용하는게 좋을 것 같아요! 이젠 IBAction은 최대한 활용하지 않는 쪽으로 가는게 도움이 될 것 같아요:)
`button.rx.tap.bind{...}`
위에 코드처럼 고쳐주세요!

2021-10-19 13:45 UTC, MoonJisu commented on Color/Color/VC/WritingPageViewController.swift
> +class WritingPageViewController: UIViewController, UITextViewDelegate, UITextFieldDelegate {
Delagte는 extension으로 빼서 정리하면 더 깔끔할 것 같아요

2021-10-19 13:45 UTC, MoonJisu commented on Color/Color/VC/WritingPageViewController.swift
> +        let buttonAndConceptColor : [String : UIButton] = ["angry": redButton, "happy": yellowButton, "sad": blueButton, "bored": grayButton, "love": pinkButton, "shamed": navyButton]
이 배열을 리소스 관리하는 클래스에 넣어도 좋을 것 같아요!

2021-10-19 13:46 UTC, jangseoyoung commented on Color/Color/VC/WritingPageViewController.swift
> +        let buttonAndConceptColor : [String : UIButton] = ["angry": redButton, "happy": yellowButton, "sad": blueButton, "bored": grayButton, "love": pinkButton, "shamed": navyButton]
리소스 관리하는 클래스를 하나 만들어서 관리하라는 뜻이죠??

2021-10-19 15:03 UTC, MoonJisu commented on Color/Color/VC/WritingPageViewController.swift
> +        let buttonAndConceptColor : [String : UIButton] = ["angry": redButton, "happy": yellowButton, "sad": blueButton, "bored": grayButton, "love": pinkButton, "shamed": navyButton]
네!

2021-10-20 01:35 UTC, Ga-yo requested changes
그래모에서 했던 리뷰도 까먹지 말고 적용하면 좋을 것 같아요!!

2021-10-20 01:35 UTC, Ga-yo commented on Color/Color/VC/WritingPageViewController.swift
> +                doneButton.isEnabled = false
여기 else if랑 else문에서 중복코드인 것 같은데 굳이 else if로 구분지어야하는 이유가 따로 있나요??

2021-10-20 01:35 UTC, Ga-yo commented on Color/Color/VC/WritingPageViewController.swift
> +        if textView.text.isEmpty {
이것도 delegate 메소드 안쓰고 textview.rx.text.isEmpty 이런걸로 대체할 수 있을 것 같아요!

2021-10-20 01:35 UTC, Ga-yo commented on Color/Color/VC/WritingPageViewController.swift
> +        if textView.textColor == UIColor.lightGray{
이런 textview delegate는 Rx를 쓸 땐 굳이 저렇게 안하고 
```
textfield.rx.controlEvent([.EditingDidBegin]).asObservable().subscribe(on:{_ in 
    print("edit begin")
 }).addDisposableTo(disposer)
```

대충 이렇게 응용할 수 있어요 
textview말고도 다른 오브젝트들도 활용할 수 있습니다 :)

2021-10-26 10:15 UTC, merged